### PR TITLE
🔨 debug scripts

### PR DESCRIPTION
**Pull request by nuts-rice**
Some scripts to hopefully help with debugging 
Includes [flamegraphs](https://brendangregg.com/flamegraphs.html)   and [cachegrind](https://valgrind.org/docs/manual/cg-manual.html#cg-manual.overview) as bash scripts  
These could be merged into existing devshell .nix flakes if needed
the cachegrind script right now is timeouted to 60s and aggregates and diffs across multiple outputs 
flamegraph takes a bit after killing blutgang to write out the svg file

### CODE REVIEW

**Comment by nuts-rice** [comment]
needed to say that this needs cargo-flamegraph
`cargo install flamegraph`

**Comment by makemake-kbo** [comment]
works on nixos, lmk when ready to merge

**Comment by nuts-rice** [comment]
> > needed to say that this needs cargo-flamegraph `cargo install flamegraph`
> 
> this might be broken on nix, ill see how to add this to the nix flake and then merge

I added some installation conditional checks for perf and cargo-flamefraph

**Comment by nuts-rice** [comment]
> works on nixos, lmk when ready to merge
go ahead : P

**Pull request merged**
