### PR TITLE
Add proper k8s liveness/readiness checks

### PR DESCRIPTION
**Pull request by makemake-kbo**

### CODE REVIEW

**Comment by derekbar90** [comment]
much needed! Great add

**Comment by makemake-kbo** [comment]
looks good enough for merge, should test a bit more tho

**Comment by barnabasbusa** [comment]
can you make a one off img build of this branch? Can help testing

**Comment by makemake-kbo** [comment]
docker pull makemake1337/blutgang:live-ready-986ea0

Health and readiness are located at `/health` and `/ready` on the admin api.  
`200` is returned if things are nominal.
`202` is returned on `/health` if some RPCs are unhealthy. `/ready` will still return `200`.
`503` will be returned on `/health` if all RPCs are down. `503` on `/ready` means that blutgang is starting up and unable to accept requests. `503` on `/ready` will only occur on initial boot. if all rpcs are down `/ready` will still return `200`

**Comment by makemake-kbo** [comment]
Pushed new container with fixes: https://hub.docker.com/layers/makemake1337/blutgang/live-ready-3bb39f/images/sha256-d493d6dd40fc92f2c7279582c5598091d7edbd9942c655a5c85c42d6aba4b466?context=explore

**Comment by makemake-kbo** [comment]
https://hub.docker.com/layers/makemake1337/blutgang/live-ready-127464/images/sha256-20bac57e91c77e6e91f3b43d0578933bb46da6e3a2d26436de6ceb9800548d9b?context=explore

**Comment by makemake-kbo** [comment]
Closed in favor of: https://github.com/rainshowerLabs/blutgang/pull/68

**Pull request closed without merging**
